### ISSUE TITLE
Bug in deletion algorithm

### ISSUE THREAD

**Issue by igrmk** [logrusorgru/ebony#2]
There is a bug in deletion algorithm that affects sentinel.
Following PR provides assertions to catch it https://github.com/logrusorgru/ebony/pull/1

Basically during deletion `sentinel.parent` is invalidated and points to node rather than nil.
However if you fix just that bug then fixup part stops working.
Looks like deletion algorithm needs thorough revision.

**Comment by logrusorgru** [comment]
It's allowed by the algorithm. Not a bug.
